[package]
name = "rslox1"
version = "0.1.0"
edition = "2018"

[dependencies]
either = "1.7.0"
option-ext = "0.2.0"
nonempty = "0.8.1"
num-derive = "0.4.0"
num-traits = "0.2"

[dev-dependencies]
pretty_assertions_sorted = "1.2.3"
